import type { Metadata } from "next";
import { DomainSearch } from "@/components/domain-search";
import { ProductHero, SiteFrame } from "@/components/hostmyweb-site-chrome";

export const metadata: Metadata = { title: "Domains", description: "Search, register, renew, transfer, and manage domains through HostMyWeb with renewal pricing shown up front." };

const domains = [{tld:".com",price:"$17.99"},{tld:".org",price:"$17.99"},{tld:".net",price:"$19.99"},{tld:".us",price:"$14.99"}] as const;

export default function DomainsPage() {
  return <SiteFrame><ProductHero eyebrow="Domains" title="Your domain without" accent="the year-two surprise." description="Search availability, register or transfer a domain, manage DNS, and see the listed registration and renewal price before you buy." /><section className="hmw-product-shell"><div className="hmw-section-head"><div><span className="hmw-eyebrow"><i /> DOMAIN SEARCH</span><h2>Find the name first.</h2><p>Search current availability and move into account or checkout flow when you find the domain you want.</p></div></div><div className="hmw-domain-box"><DomainSearch /></div></section><section id="pricing" className="hmw-section alt"><div className="hmw-section-head"><div><span className="hmw-eyebrow"><i /> DOMAIN PRICING</span><h2>Registration and renewal together.</h2><p>No temporary “free domain” headline hiding a completely different renewal price.</p></div></div><div className="hmw-category-grid">{domains.map((item)=><article className="hmw-category-card" key={item.tld}><small>DOMAIN</small><h3>{item.tld}</h3><p>Registration & renewal</p><b>{item.price}/yr</b></article>)}</div></section><section id="transfer" className="hmw-section dark"><div className="hmw-section-head"><div><span className="hmw-eyebrow"><i /> TRANSFERS</span><h2>Bring an existing domain to HostMyWeb.</h2><p>Domain transfer is separate from website migration. A domain can move registrars without rebuilding the website, while website files, databases, and mailboxes use the migration process.</p></div><a className="hmw-button secondary" href="/support">Ask about a transfer</a></div><div className="hmw-proof-grid"><article><small>01</small><b>Domain transfer</b><p>Move registrar management for an eligible domain into HostMyWeb.</p></article><article><small>02</small><b>DNS management</b><p>Control records connecting the domain to websites, email, and other services.</p></article><article><small>03</small><b>Website migration</b><p>Move site files and databases separately through the website migration service.</p></article><article><small>04</small><b>Email continuity</b><p>Plan DNS and mailbox transitions carefully when email is already active on the domain.</p></article></div></section></SiteFrame>;
}
