import type { Metadata } from "next";
import { ProductHero, SiteFrame } from "@/components/hostmyweb-site-chrome";

export const metadata: Metadata = { title: "Security & Performance", description: "HostMyWeb SSL, CDN, backups, malware scanning, WAF, DDoS protection, Website Turbo, premium SSL, and recovery options." };

const addOns = [
  { title: "Website Turbo", text: "High-frequency performance acceleration for eligible demanding hosted sites.", meta: "Performance add-on", href: "/products/website-turbo" },
  { title: "Premium SSL Certificates", text: "Optional paid certificate products while standard hosted HTTPS remains included.", meta: "Security add-on", href: "/products/premium-ssl" },
  { title: "Timeline Backups Pro", text: "Extended snapshot-style recovery for customers who need deeper restore history.", meta: "Recovery add-on", href: "/products/timeline-backups" },
  { title: "Malware Cleanup & Recovery", text: "Hands-on investigation, cleanup, restore, and relaunch assistance after a security incident.", meta: "Service", href: "/products/malware-cleanup" },
] as const;

export default function SecurityPage() {
  return <SiteFrame><ProductHero eyebrow="Security & Performance" title="The protections around" accent="the website." description="Core hosting includes the everyday security and delivery layer. HostMyWeb also offers paid performance, certificate, recovery, and hands-on security products for customers who need more." /><section className="hmw-product-shell"><div className="hmw-section-head"><div><span className="hmw-eyebrow"><i /> INCLUDED LAYER</span><h2>Start with the protections a hosting plan should already have.</h2></div></div><div className="hmw-feature-list"><article><small>SSL</small><b>Standard SSL</b><p>Encrypt ordinary hosted website connections without making basic HTTPS a surprise checkout fee.</p></article><article><small>CDN</small><b>Global CDN</b><p>Distribute cacheable content through a worldwide delivery layer.</p></article><article><small>MALWARE</small><b>Malware scanning</b><p>Use hosting security tools to identify suspicious website files and activity.</p></article><article><small>WAF</small><b>Application firewall</b><p>Help reduce common automated threats at the web-application layer.</p></article><article><small>DDoS</small><b>DDoS protection</b><p>Use network-level protections as part of the broader hosting platform.</p></article><article><small>BACKUPS</small><b>Backup & restore</b><p>Recover website data when a change, failure, or incident requires restoration.</p></article></div></section><section className="hmw-section alt"><div className="hmw-section-head"><div><span className="hmw-storefront-kicker">OPTIONAL PRODUCTS</span><h2>Upgrade only the part you actually need.</h2><p>Performance acceleration, premium certificates, deeper backup history, and hands-on cleanup now have distinct product paths instead of being vague future bullets.</p></div><a className="hmw-text-link" href="/products">Full product catalog →</a></div><div className="hmw-index-grid">{addOns.map((item) => <a className="hmw-index-link" href={item.href} key={item.title}><div><small>{item.meta}</small><h3>{item.title}</h3><p>{item.text}</p></div><span>→</span></a>)}</div></section></SiteFrame>;
}
